//
// Created by Nickid2018 on 2023/7/16.
//

#include "je_protocol_constants.h"

wmem_map_t *protocol_name_map_client_je;
wmem_map_t *protocol_name_map_server_je;

#define DEFINE_NAME_CLIENT(name, desc) wmem_map_insert(protocol_name_map_client_je, #name, #desc);
#define DEFINE_NAME_SERVER(name, desc) wmem_map_insert(protocol_name_map_server_je, #name, #desc);

void init_je_constants() {
    protocol_name_map_client_je = wmem_map_new(wmem_epan_scope(), g_str_hash, g_str_equal);
    protocol_name_map_server_je = wmem_map_new(wmem_epan_scope(), g_str_hash, g_str_equal);

    // Login
    DEFINE_NAME_CLIENT(disconnect, Client Login Disconnect)
    DEFINE_NAME_CLIENT(encryption_begin, Client Hello)
    DEFINE_NAME_CLIENT(success, Client Login Success)
    DEFINE_NAME_CLIENT(compress, Client Compression)
    DEFINE_NAME_CLIENT(login_plugin_request, Client Custom Query)
    DEFINE_NAME_SERVER(login_start, Server Hello)
    DEFINE_NAME_SERVER(encryption_begin, Server Key)
    DEFINE_NAME_SERVER(login_plugin_response, Server Custom Query)
    DEFINE_NAME_SERVER(login_acknowledgement, Server Login Success ACK)
    // Play
    DEFINE_NAME_CLIENT(bundle_delimiter, Client Bundle Delimter)
    DEFINE_NAME_CLIENT(spawn_entity, Client Add Entity)
    DEFINE_NAME_CLIENT(spawn_entity_experience_orb, Client Add Experience Orb)
    DEFINE_NAME_CLIENT(named_entity_spawn, Client Add Player)
    DEFINE_NAME_CLIENT(animation, Client Animation)
    DEFINE_NAME_CLIENT(statistics, Client Award Statistics)
    DEFINE_NAME_CLIENT(acknowledge_player_digging, Client Block Changed ACK)
    DEFINE_NAME_CLIENT(block_break_animation, Client Block Destruction)
    DEFINE_NAME_CLIENT(tile_entity_data, Client Block Entity Data)
    DEFINE_NAME_CLIENT(block_action, Client Block Action)
    DEFINE_NAME_CLIENT(block_change, Client Block Event)
    DEFINE_NAME_CLIENT(boss_bar, Client Boss Event)
    DEFINE_NAME_CLIENT(difficulty, Client Change Difficulty)
    DEFINE_NAME_CLIENT(chunk_biomes, Client Chunks Biomes)
    DEFINE_NAME_CLIENT(clear_titles, Client Clear Titles)
    DEFINE_NAME_CLIENT(tab_complete, Client Command Suggestions)
    DEFINE_NAME_CLIENT(declare_commands, Client Commands)
    DEFINE_NAME_CLIENT(close_window, Client Container Close)
    DEFINE_NAME_CLIENT(window_items, Client Container Set Content)
    DEFINE_NAME_CLIENT(craft_progress_bar, Client Container Set Data)
    DEFINE_NAME_CLIENT(set_slot, Client Container Set Slot)
    DEFINE_NAME_CLIENT(set_cooldown, Client Cooldown)
    DEFINE_NAME_CLIENT(chat_suggestions, Client Custom Chat Completations)
    DEFINE_NAME_CLIENT(custom_payload, Client Custom Payload)
    DEFINE_NAME_CLIENT(damage_event, Client Damage Event)
    DEFINE_NAME_CLIENT(hide_message, Client Delete Chat)
    DEFINE_NAME_CLIENT(kick_disconnect, Client Disconnect)
    DEFINE_NAME_CLIENT(profileless_chat, Client Disguised Chat)
    DEFINE_NAME_CLIENT(entity_status, Client Entity Event)
    DEFINE_NAME_CLIENT(explosion, Client Explode)
    DEFINE_NAME_CLIENT(unload_chunk, Client Forget Level Chunk)
    DEFINE_NAME_CLIENT(game_state_change, Client Game Event)
    DEFINE_NAME_CLIENT(open_horse_window, Client Horse ScreenOpen)
    DEFINE_NAME_CLIENT(hurt_animation, Client Hurt Animation)
    DEFINE_NAME_CLIENT(initialize_world_border, Client Initialize Border)
    DEFINE_NAME_CLIENT(keep_alive, Client Keep Alive)
    DEFINE_NAME_CLIENT(map_chunk, Client Level Chunk with Light)
    DEFINE_NAME_CLIENT(world_event, Client Level Event)
    DEFINE_NAME_CLIENT(world_particles, Client Level Particles)
    DEFINE_NAME_CLIENT(update_light, Client Light Update)
    DEFINE_NAME_CLIENT(login, Client Login)
    DEFINE_NAME_CLIENT(map, Client Map Item Data)
    DEFINE_NAME_CLIENT(trade_list, Client Merchant Offers)
    DEFINE_NAME_CLIENT(rel_entity_move, Client Move Entity Position)
    DEFINE_NAME_CLIENT(entity_move_look, Client Move Entity Position & Rotation)
    DEFINE_NAME_CLIENT(entity_look, Client Move Entity Rotation)
    DEFINE_NAME_CLIENT(vehicle_move, Client Move Vehicle)
    DEFINE_NAME_CLIENT(open_book, Client Open Book)
    DEFINE_NAME_CLIENT(open_window, Client Open Screen)
    DEFINE_NAME_CLIENT(open_sign_entity, Client Open Sign Editor)
    DEFINE_NAME_CLIENT(ping, Client Ping)
    DEFINE_NAME_CLIENT(craft_recipe_response, Client Place Ghost Recipe)
    DEFINE_NAME_CLIENT(abilities, Client Player Abilities)
    DEFINE_NAME_CLIENT(player_chat, Client Player Chat)
    DEFINE_NAME_CLIENT(end_combat_event, Client Player Combat End)
    DEFINE_NAME_CLIENT(enter_combat_event, Client Player Combat Enter)
    DEFINE_NAME_CLIENT(death_combat_event, Client Player Combat Kill)
    DEFINE_NAME_CLIENT(player_remove, Client Player Info Remove)
    DEFINE_NAME_CLIENT(player_info, Client Player Info Update)
    DEFINE_NAME_CLIENT(face_player, Client Player Look at)
    DEFINE_NAME_CLIENT(position, Client Player Position)
    DEFINE_NAME_CLIENT(unlock_recipes, Client Recipe)
    DEFINE_NAME_CLIENT(entity_destroy, Client Remove Entities)
    DEFINE_NAME_CLIENT(remove_entity_effect, Client Remove Mob Effect)
    DEFINE_NAME_CLIENT(resource_pack_send, Client Resource Pack)
    DEFINE_NAME_CLIENT(respawn, Client Respawn)
    DEFINE_NAME_CLIENT(entity_head_rotation, Client Rotate Head)
    DEFINE_NAME_CLIENT(multi_block_change, Client Section Blocks Update)
    DEFINE_NAME_CLIENT(select_advancement_tab, Client Select Advancement Tab)
    DEFINE_NAME_CLIENT(server_data, Client Server Data)
    DEFINE_NAME_CLIENT(action_bar, Client Set Action Bar Text)
    DEFINE_NAME_CLIENT(world_border_center, Client Set Border Center)
    DEFINE_NAME_CLIENT(world_border_lerp_size, Client Set Border Lerp Size)
    DEFINE_NAME_CLIENT(world_border_size, Client Set Border Size)
    DEFINE_NAME_CLIENT(world_border_warning_delay, Client Set Border Warning Delay)
    DEFINE_NAME_CLIENT(world_border_warning_reach, Client Set Border Warning Distance)
    DEFINE_NAME_CLIENT(camera, Client Set Camera)
    DEFINE_NAME_CLIENT(held_item_slot, Client Set Carried Item)
    DEFINE_NAME_CLIENT(update_view_position, Client Set Chunk Cache Center)
    DEFINE_NAME_CLIENT(update_view_distance, Client Set Chunk Cache Radius)
    DEFINE_NAME_CLIENT(spawn_position, Client Set Default Spawn Position)
    DEFINE_NAME_CLIENT(scoreboard_display_objective, Client Set Display Objective)
    DEFINE_NAME_CLIENT(entity_metadata, Client Set Entity Data)
    DEFINE_NAME_CLIENT(attach_entity, Client Set Entity Link)
    DEFINE_NAME_CLIENT(entity_velocity, Client Set Entity Motion)
    DEFINE_NAME_CLIENT(entity_equipment, Client Set Equipment)
    DEFINE_NAME_CLIENT(experience, Client Set Experience)
    DEFINE_NAME_CLIENT(update_health, Client Set Health)
    DEFINE_NAME_CLIENT(scoreboard_objective, Client Set Objective)
    DEFINE_NAME_CLIENT(set_passengers, Client Set Passengers)
    DEFINE_NAME_CLIENT(teams, Client Set Player Team)
    DEFINE_NAME_CLIENT(scoreboard_score, Client Set Score)
    DEFINE_NAME_CLIENT(simulation_distance, Client Set Simulation Distance)
    DEFINE_NAME_CLIENT(set_title_subtitle, Client Set Subtitle Text)
    DEFINE_NAME_CLIENT(update_time, Client Set Time)
    DEFINE_NAME_CLIENT(set_title_text, Client Set Title Text)
    DEFINE_NAME_CLIENT(set_title_time, Client Set Titles Animation)
    DEFINE_NAME_CLIENT(entity_sound_effect, Client Sound Entity)
    DEFINE_NAME_CLIENT(sound_effect, Client Sound)
    DEFINE_NAME_CLIENT(stop_sound, Client Stop Sound)
    DEFINE_NAME_CLIENT(system_chat, Client System Chat)
    DEFINE_NAME_CLIENT(playerlist_header, Client Tab List)
    DEFINE_NAME_CLIENT(nbt_query_response, Client Tag Query)
    DEFINE_NAME_CLIENT(collect, Client Take Item Entity)
    DEFINE_NAME_CLIENT(entity_teleport, Client Teleport Entity)
    DEFINE_NAME_CLIENT(advancements, Client Update Advancements)
    DEFINE_NAME_CLIENT(entity_update_attributes, Client Update Attributes)
    DEFINE_NAME_CLIENT(feature_flags, Client Update Enabled Features)
    DEFINE_NAME_CLIENT(entity_effect, Client Update Mob Effect)
    DEFINE_NAME_CLIENT(declare_recipes, Client Update Recipes)
    DEFINE_NAME_CLIENT(tags, Client Update Tags)
    DEFINE_NAME_CLIENT(chunk_batch_finished, Client Chunk Batch Finished)
    DEFINE_NAME_CLIENT(chunk_batch_start, Client Chunk Batch Start)
    DEFINE_NAME_CLIENT(start_configuration, Client Start Configuration)
    DEFINE_NAME_SERVER(teleport_confirm, Server Accept Teleportation)
    DEFINE_NAME_SERVER(query_block_nbt, Server Block Entity Tag Query)
    DEFINE_NAME_SERVER(set_difficulty, Server Change Difficulty)
    DEFINE_NAME_SERVER(message_acknowledgement, Server Chat ACK)
    DEFINE_NAME_SERVER(chat_command, Server Chat Command)
    DEFINE_NAME_SERVER(chat_message, Server Chat)
    DEFINE_NAME_SERVER(chat_session_update, Server Chat Session Update)
    DEFINE_NAME_SERVER(client_command, Server Client Command)
    DEFINE_NAME_SERVER(settings, Server Client Information)
    DEFINE_NAME_SERVER(tab_complete, Server Command Suggestion)
    DEFINE_NAME_SERVER(enchant_item, Server Container Button Click)
    DEFINE_NAME_SERVER(window_click, Server Container Click)
    DEFINE_NAME_SERVER(close_window, Server Container Close)
    DEFINE_NAME_SERVER(custom_payload, Server Custom Payload)
    DEFINE_NAME_SERVER(edit_book, Server Edit Book)
    DEFINE_NAME_SERVER(query_entity_nbt, Server Entity Tag Query)
    DEFINE_NAME_SERVER(use_entity, Server Interact)
    DEFINE_NAME_SERVER(generate_structure, Server Jigsaw Generate)
    DEFINE_NAME_SERVER(keep_alive, Server Keep Alive)
    DEFINE_NAME_SERVER(lock_difficulty, Server Lock Difficulty)
    DEFINE_NAME_SERVER(position, Server Move Player Position)
    DEFINE_NAME_SERVER(position_look, Server Move Player Position & Rotation)
    DEFINE_NAME_SERVER(look, Server Move Player Rotation)
    DEFINE_NAME_SERVER(flying, Server Move Player Status-Only)
    DEFINE_NAME_SERVER(vehicle_move, Server Move Vehicle)
    DEFINE_NAME_SERVER(steer_boat, Server Paddle Boat)
    DEFINE_NAME_SERVER(pick_item, Server Pick Item)
    DEFINE_NAME_SERVER(craft_recipe_request, Server Place Recipe)
    DEFINE_NAME_SERVER(abilities, Server Player Abilities)
    DEFINE_NAME_SERVER(block_dig, Server Player Action)
    DEFINE_NAME_SERVER(entity_action, Server Player Command)
    DEFINE_NAME_SERVER(steer_vehicle, Server Player Input)
    DEFINE_NAME_SERVER(pong, Server Pong)
    DEFINE_NAME_SERVER(recipe_book, Server Recipe Book Change Settings)
    DEFINE_NAME_SERVER(displayed_recipe, Server Recipe Book Seen Recipe)
    DEFINE_NAME_SERVER(name_item, Server Rename Item)
    DEFINE_NAME_SERVER(resource_pack_receive, Server Resource Pack)
    DEFINE_NAME_SERVER(advancement_tab, Server Seen Advancements)
    DEFINE_NAME_SERVER(select_trade, Server Select Trade)
    DEFINE_NAME_SERVER(set_beacon_effect, Server Set Beacon)
    DEFINE_NAME_SERVER(held_item_slot, Server Set Carried Item)
    DEFINE_NAME_SERVER(update_command_block, Server Set Command Block)
    DEFINE_NAME_SERVER(update_command_block_minecart, Server Set Command Minecart)
    DEFINE_NAME_SERVER(set_creative_slot, Server Set Creative Mode Slot)
    DEFINE_NAME_SERVER(update_jigsaw_block, Server Set Jigsaw Block)
    DEFINE_NAME_SERVER(update_structure_block, Server Set Structure Block)
    DEFINE_NAME_SERVER(update_sign, Server Sign Update)
    DEFINE_NAME_SERVER(arm_animation, Server Swing)
    DEFINE_NAME_SERVER(spectate, Server Teleport To Entity)
    DEFINE_NAME_SERVER(block_place, Server Use Item on)
    DEFINE_NAME_SERVER(use_item, Server Use Item)
    DEFINE_NAME_SERVER(chunk_batch_received, Server Chunk Batch Received)
    DEFINE_NAME_SERVER(configuration_acknowledgement, Server Configuration ACK)
    // Configuration
    DEFINE_NAME_CLIENT(finish_configuration, Client Finish Configuration)
    DEFINE_NAME_CLIENT(registry_data, Client Registry Data)
    DEFINE_NAME_SERVER(finish_configuration, Server Finish Configuration)
}